version: "3.9"

services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-postgres
    ports:
      - "5432:5432"
